import java.io.Serializable;
import java.util.ArrayList;
import java.util.Objects;

public abstract class Animal implements Serializable {

        protected AutoGeneratedID autoGeneratedID = AutoGeneratedID.getInstance("IdSet.txt");

        protected int id;
        public String type;      // type of Animal "BeefCow","DairyCow","Goat", "Sheep" ...
        protected int age;          // age of the Animal
        protected double weight;    // weight of the Animal


    public Animal( int age) {
        this.id = autoGeneratedID.getNextId();
        this.type = type;
        this.age = age;
        this.weight = weight;

    }

    public Animal(String type, int age, double weight) {
        this.id = autoGeneratedID.getNextId();
        this.type = type;
        this.age = age;
        this.weight = weight;

    }

    public Animal(int id, String type, int age, double weight) {
        this.id = id;
        this.type = type;
        this.age = age;
        this.weight = weight;

    }



    public int getId() {
        return id;
    }

    public String getType() {
        return type;
    }

    public int getAge() {
        return age;
    }

    public double getWeight() {
        return weight;
    }

    public void setId(int id) {

    } //not returning an id as it only come from AutoGenerator

    public void setType(String type) {
        this.type = type;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Animal animal = (Animal) o;
        return type.equals(animal.type);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(type);
    }



    public String showInfo() {

        return
                "autoGeneratedID = " + autoGeneratedID +
                ", type = " + type  +
                ", age = " + age +
                ", weight = " + weight ;
    }



}
