import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class AutoGeneratedID {

    private static AutoGeneratedID autoGeneratedID; // instance referenced to this class
    private int nextId;
    private String fileName;


    private AutoGeneratedID(String fileName) {
        this.fileName = fileName;
        // open file
        try {
            File file = new File(fileName);
            Scanner scanner = new Scanner(file);
            while (scanner.hasNext()) {
                nextId = scanner.nextInt();
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            System.out.println("Fail from reading File: IdSet.txt");
            e.printStackTrace();
        }
    }

    public static AutoGeneratedID getInstance(String fileName) {
        if (autoGeneratedID == null) {
            autoGeneratedID = new AutoGeneratedID(fileName);
        }
        return autoGeneratedID;
    }


    public int getNextId() {
        File file = new File(fileName);
        FileWriter fWriter = null;
        try {
            fWriter = new FileWriter(file);
            fWriter.write(Integer.toString(nextId+3));
        } catch (IOException e) {
            e.printStackTrace();
        }finally{


            try {
                fWriter.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        return nextId++;
    }





}
