import java.io.Serializable;
import java.util.Random;

public class BeefCow extends Animal implements Serializable {

    private String name;
    private String pedigree;

    private final String[] NAMES = new String[]{
            "beef1", "beef2", "beef3", "beef4", "beef5",
            "beef6", "beef7", "beef8", "beef9", "beef10",
            "beef11", "beef12", "beef13", "beef14", "beef15",
            "beef16", "beef17", "beef18", "beef19", "beef20",
            "beef21", "beef22", "beef23", "beef24", "beef25",
            "beef26", "beef27", "beef28", "beef29", "beef30",};
    String nameBeefCow = NAMES[new Random().nextInt(NAMES.length) ];

    public BeefCow(String type, int age, double weight, String name, String pedigree) {
        super(type, age, weight);
//        this.id = autoGeneratedID.getNextId();
        this.pedigree = pedigree;
        this.name = nameBeefCow;
    }

    public BeefCow(int id, String type, int age, double weight, String name, String pedigree) {
        super(id, type, age, weight);
//        this.id = autoGeneratedID.getNextId();
        this.pedigree = pedigree;
        this.name = nameBeefCow;
    }

//    public BeefCow(String name, int age, double weight, String pedigree) {
//        this.name = name;
//        this.age = age;
//        this.weight = weight;
//        this.pedigree = pedigree;
//    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPedigree() {
        return pedigree;
    }

    public void setPedigree(String pedigree) {
        this.pedigree = pedigree;
    }

    @Override
    public String showInfo() {

        return
                "autoGeneratedID=" + autoGeneratedID +
                        ", type='" + type  +
                        ", age=" + age +
                        ", weight=" + weight +
                        ", name=" + name  +
                        ", pedigree=" + pedigree ;
    }

}
