import java.util.Objects;

public class Farm {

    private int id;
    private String name;
    private String email;
    private String phone;


    private AutoGeneratedID autoGeneratedID = AutoGeneratedID.getInstance("IdSet.txt");

    public Farm(String name, String email, String phone) {

        // some minimal validation
        if (name == null )
            throw new IllegalArgumentException("null arguments encountered");

        this.id = autoGeneratedID.getNextId();
        this.name = name;
        this.email = email;
        this.phone = phone;

    }

    public Farm(int id, String name, String email, String phone) {

        if (name == null)
            throw new IllegalArgumentException("NULL ELEMENTS");

        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;

    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public String getPhone() {
        return phone;
    }

    public AutoGeneratedID getAutoGeneratedID() {
        return autoGeneratedID;
    }

    public void setId() {
        ////IT WILL BECOME ONLY FROM THE GENERATOR
    }


    public void setName(String name) {
        this.name = name;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public void setAutoGeneratedID(AutoGeneratedID autoGeneratedID) {
        this.autoGeneratedID = autoGeneratedID;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Farm farm = (Farm) o;
        return name.equals(farm.name) && email.equals(farm.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, email);
    }


    @Override
    public String toString() {
        return "Farm{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' + '}';
    }
}
