import java.io.Serializable;
import java.util.Random;

public class Sheep extends Animal implements Serializable {

    private String name;
    private String pedigree;



    private final String[] NAMES = new String[]{
            "Sheep1", "Sheep2", "Sheep3", "Sheep4", "Sheep5",
            "Sheep6", "Sheep7", "Sheep8", "Sheep9", "Sheep10",
            "Sheep11", "Sheep12", "Sheep13", "Sheep14", "Sheep15",
            "Sheep16", "Sheep17", "Sheep18", "Sheep19", "Sheep20",
            "Sheep21", "Sheep22", "Sheep23", "Sheep24", "Sheep25",
            "Sheep26", "Sheep27", "Sheep28", "Sheep29", "Sheep30",};
    String nameSheep = NAMES[new Random().nextInt(NAMES.length) ];


    public Sheep(int id, String type, int age, double weight, String name, String pedigree) {
        super(type, age, weight);
        this.id = autoGeneratedID.getNextId();
        this.pedigree = pedigree;
        this.name = nameSheep;
    }


//    public Sheep(int autoGeneratedID, String type, int age, double weight, String name, String pedigree) {
//        super(autoGeneratedID, type, age, weight);
//        this.name = name;
//        this.pedigree = pedigree;
//
//    }

//    public BeefCow(String name, int age, double weight, String pedigree) {
//        this.name = name;
//        this.age = age;
//        this.weight = weight;
//        this.pedigree = pedigree;
//    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPedigree() {
        return pedigree;
    }

    public void setPedigree(String pedigree) {
        this.pedigree = pedigree;
    }

    @Override
    public String showInfo() {

        return
                "autoGeneratedID=" + autoGeneratedID +
                        ", type='" + type  +
                        ", age=" + age +
                        ", weight=" + weight +
                        ", name=" + name  +
                        ", pedigree=" + pedigree ;
    }

}
