import java.io.Serializable;

public class Sheep extends Animal implements Serializable {

    private String name;
    private String pedigree;

    public Sheep(int autoGeneratedID, String type, int age, double weight, String name, String pedigree) {
        super(autoGeneratedID, type, age, weight);
        this.name = name;
        this.pedigree = pedigree;

    }

//    public BeefCow(String name, int age, double weight, String pedigree) {
//        this.name = name;
//        this.age = age;
//        this.weight = weight;
//        this.pedigree = pedigree;
//    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPedigree() {
        return pedigree;
    }

    public void setPedigree(String pedigree) {
        this.pedigree = pedigree;
    }

    @Override
    public String showInfo() {

        return
                "autoGeneratedID=" + autoGeneratedID +
                        ", type='" + type  +
                        ", age=" + age +
                        ", weight=" + weight +
                        ", name=" + name  +
                        ", pedigree=" + pedigree ;
    }

}
